parameters:
     jarves.core.class: Jarves\Jarves
     jarves.config.class: Jarves\JarvesConfig
     jarves.objects.class: Jarves\Objects
     jarves.content.render.class: Jarves\ContentRender
     jarves.routes.loader: Jarves\Router\FrontendLoader
     jarves.rest.routing_loader.class: Jarves\Router\RestApiLoader

     jarves.acl.class: Jarves\ACL

     jarves.navigation.class: Jarves\Navigation
     jarves.stopwatch.class: Jarves\StopwatchHelper
     jarves.translator.class: Jarves\Translation\Translator

     jarves.pluginResponse.listener.class: Jarves\EventListener\PluginResponseListener
     jarves.paramFetcher.listener.class: Jarves\EventListener\ParamFetcherListener
     jarves.securityFirewall.listener.class: Jarves\EventListener\SecurityFirewallListener
     jarves.termination.listener.class: Jarves\EventListener\TerminationListener
     jarves.restException.listener.class: Jarves\EventListener\RestExceptionListener
     jarves.viewResponse.listener.class: Jarves\EventListener\ViewResponseListener
     jarves.frontendRoutes.listener.class: Jarves\EventListener\FrontendRouteListener
     jarves.debugger.subscriber.class: Jarves\EventListener\DebuggerSubscriber
     jarves.latencyMonitor.subscriber.class: Jarves\EventListener\LatencyMonitorSubscriber

     jarves.cache.factory.class: Jarves\Cache\Backend\Factory
     jarves.cache.fast.class: Jarves\Cache\Backend\AbstractCache
     jarves.cache.response_cacher.class: Jarves\Cache\ResponseCacher
     jarves.cache.cacher.class: Jarves\Cache\Cacher

     jarves.logger.handler.class: Jarves\Logger\JarvesHandler

     jarves.filesystem.local.class: Jarves\Filesystem\Filesystem
     jarves.filesystem.cache.class: Jarves\Filesystem\Filesystem
     jarves.filesystem.web.class: Jarves\Filesystem\WebFilesystem
     jarves.filesystem.adapter.local.class: Jarves\Filesystem\Adapter\Local

     jarves.model.builder.class: Jarves\ORM\Builder\Builder
     jarves.model.builder.propel.class: Jarves\ORM\Builder\Propel

     jarves.configuration.database.class: Jarves\Configuration\Database

     jarves.configuration.database.connection.main.class: Jarves\Configuration\Connection

     jarves.asset_handler.scss.class: Jarves\AssetHandler\ScssHandler
     jarves.asset_handler.css.class: Jarves\AssetHandler\CssHandler
     jarves.asset_handler.js.class: Jarves\AssetHandler\JsHandler
     jarves.asset_handler.container.class: Jarves\AssetHandler\Container

     database_table_prefix: jarves_
     jarves_admin_prefix: /jarves

services:
     jarves:
         class: "%jarves.core.class%"
         arguments: ["@jarves.config", "%jarves_admin_prefix%", "%kernel.cache_dir%", "%kernel.root_dir%", "%kernel.environment%", "%kernel.debug%", "@kernel", "@request_stack", "@event_dispatcher", "@jarves.field.types"]

     jarves.config:
         class: "%jarves.config.class%"
         arguments: ["%kernel.root_dir%", "%kernel.environment%", "@service_container"]

     jarves.objects:
         class: "%jarves.objects.class%"
         arguments: ["@jarves", "@service_container"]

     jarves.event_dispatcher:
         class: Jarves\JarvesEventDispatcher
         arguments: ["@event_dispatcher", "@service_container", "@jarves.condition_operator", "@jarves.cache.cacher"]

     jarves.page_stack:
         class: Jarves\PageStack
         arguments: ["%jarves_admin_prefix%", "@request_stack", "@jarves.client.factory", "@jarves.cache.cacher"]

     jarves.utils:
         class: Jarves\Utils
         arguments: ["@jarves", "@jarves.page_stack", "@jarves.filesystem.local", "@jarves.filesystem.web", "@jarves.cache.cacher"]

     jarves.page_controller:
         class: Jarves\Controller\PageController
         arguments: ["@jarves", "@jarves.editmode", "@jarves.page_stack", "@jarves.acl"]

     jarves.configuration_operator:
         class: Jarves\Configuration\ConfigurationOperator
         arguments: ["@jarves.filesystem.local"]

     jarves.editmode:
         class: Jarves\EditMode
         arguments: ["@jarves.page_stack", "@request_stack", "@jarves.acl"]

     jarves.page_response.factory:
         class: Jarves\PageResponseFactory
         arguments: ["@jarves", "@jarves.page_stack", "@jarves.stopwatch", "@jarves.asset_handler.container", "@event_dispatcher", "@templating", "@jarves.editmode"]

     jarves.cache.fast:
         class: "%jarves.cache.fast.class%"
         factory: [%jarves.cache.factory.class%, createFast]
         arguments: ["@service_container", "@jarves.config"]

     jarves.cache.distributed:
         class: "%jarves.cache.fast.class%"
         factory: [%jarves.cache.factory.class%, createDistributed]
         arguments: ["@service_container", "@jarves.config"]

     jarves.content.render:
         class: "%jarves.content.render.class%"
         arguments: ["@jarves", "@jarves.stopwatch", "@jarves.editmode", "@jarves.cache.cacher", "@event_dispatcher", "@jarves.page_stack", "@templating"]

     jarves.cache.cacher:
          class: "%jarves.cache.cacher.class%"
          arguments: ["@jarves.stopwatch", "@jarves.cache.distributed", "@jarves.cache.fast"]

     jarves.cache.response_cacher:
          class: "%jarves.cache.response_cacher.class%"
          arguments: ["@jarves", "@jarves.page_stack", "@jarves.cache.cacher", "@templating", "@jarves.page_response.factory"]

     jarves.configuration.database:
         class: "%jarves.configuration.database.class%"
         calls:
            - [addConnection, ["@jarves.configuration.database.connection.main"]]
#            - [setPrefix, ["%database_table_prefix%"]]

     jarves.configuration.database.connection.main:
         class: "%jarves.configuration.database.connection.main.class%"
         calls:
            - [setType, ["%database_driver%"]]
            - [setServer, ["%database_host%"]]
            - [setPort, ["%database_port%"]]
            - [setName, ["%database_name%"]]
            - [setUsername, ["%database_user%"]]
            - [setPassword, ["%database_password%"]]

     jarves.filesystem.adapter.local:
         class: "%jarves.filesystem.adapter.local.class%"
         shared: false
         arguments: ["/"]
         calls:
             - [setJarves, ["@jarves"]]
             - [setRoot, ["%kernel.root_dir%/.."]]

     jarves.filesystem.adapter.cache:
         class: "%jarves.filesystem.adapter.local.class%"
         arguments: ["/"]
         calls:
             - [setJarves, ["@jarves"]]
             - [setRoot, ["%kernel.cache_dir%"]]

     jarves.filesystem.local:
         class: "%jarves.filesystem.local.class%"
         calls:
            - [setAdapter, ["@jarves.filesystem.adapter.local"]]

     jarves.filesystem.cache:
         class: "%jarves.filesystem.cache.class%"
         calls:
            - [setAdapter, ["@jarves.filesystem.adapter.cache"]]

     jarves.filesystem.web:
         class: "%jarves.filesystem.web.class%"
         arguments: ["@jarves", "@jarves.config", "@service_container", "@jarves.filesystem.cache"]

     jarves.navigation:
         class: "%jarves.navigation.class%"
         arguments: ["@jarves", "@jarves.cache.cacher", "@jarves.page_stack"]

     jarves.pluginResponse.listener:
        class: "%jarves.pluginResponse.listener.class%"
        arguments: ["@jarves", "@jarves.page_stack", "@jarves.frontendRoutes.listener", "@kernel", "@jarves.page_response.factory"]
        tags:
            - { name: kernel.event_listener, event: kernel.response }
            - { name: kernel.event_listener, event: kernel.view, priority: 24 }

     jarves.paramFetcher.listener:
        class: "%jarves.paramFetcher.listener.class%"
        scope: request
        arguments: ["@jarves.page_stack", "@fos_rest.request.param_fetcher"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, prioarity: 6 }

     jarves.viewResponse.listener:
        class: "%jarves.viewResponse.listener.class%"
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: 16 }

     jarves.frontendRoutes.listener:
        class: "%jarves.frontendRoutes.listener.class%"
        arguments: ["@jarves", "@jarves.page_stack", "@jarves.editmode", "@jarves.frontend_router", "@jarves.page_response.factory"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 64 }

     jarves.securityFirewall.listener:
        class: "%jarves.securityFirewall.listener.class%"
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 21 }

     jarves.termination.listener:
        class: "%jarves.termination.listener.class%"
        arguments: ["@jarves", "@jarves.page_stack"]
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, priority: -1024 }

     jarves.restException.listener:
        class: "%jarves.restException.listener.class%"
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception}

     jarves.latencyMonitor.subscriber:
        class: "%jarves.latencyMonitor.subscriber.class%"
        arguments: ["@jarves.page_stack", "@jarves.cache.distributed"]
        tags:
            - { name: kernel.event_subscriber }

     jarves.debugger.subscriber:
        class: "%jarves.debugger.subscriber.class%"
        arguments: ["@service_container", "@jarves.logger.handler"]
        tags:
            - { name: kernel.event_subscriber }

     jarves.translator:
        class: "%jarves.translator.class%"
        arguments: ["@jarves", "@jarves.cache.cacher", "@jarves.filesystem.web", "@jarves.filesystem.cache"]

     jarves.frontend_router:
        class: Jarves\Router\FrontendRouter
        arguments: ["@jarves", "@jarves.page_stack", "@jarves.stopwatch", "@logger", "@event_dispatcher", "@jarves.cache.cacher"]

     jarves.stopwatch:
        class: "%jarves.stopwatch.class%"
        arguments: ["@?debug.stopwatch"]

     jarves.condition_operator:
        class: Jarves\ConditionOperator
        arguments: ["@jarves", "@jarves.config", "@jarves.objects", "@jarves.page_stack"]

     jarves.acl:
        class: "%jarves.acl.class%"
        arguments: ["@jarves", "@jarves.objects", "@jarves.page_stack", "@jarves.cache.cacher", "@jarves.condition_operator"]

     jarves.logger.handler:
        class: "%jarves.logger.handler.class%"
        arguments: ["@jarves.page_stack"]
        
     jarves.rest.routing_loader:
        class: "%jarves.rest.routing_loader.class%"
        arguments: ["@jarves"]
        tags:
            - { name: routing.loader }

     jarves.model.builder:
        class: "%jarves.model.builder.class%"
        arguments: ["@jarves"]

     jarves.model.builder.propel:
        class: "%jarves.model.builder.propel.class%"
        arguments: ["@jarves.filesystem.local", "@jarves.objects", "@kernel"]
        tags:
            - { name: jarves.model.builder, alias: propel }

     jarves.asset_handler.container:
        arguments: ["@service_container"]
        class: "%jarves.asset_handler.container.class%"

     jarves.asset_handler.scss:
        class: "%jarves.asset_handler.scss.class%"
        arguments: ["@jarves", "@jarves.filesystem.web"]
        tags:
            - { name: jarves.asset_handler.compiler, extension: scss }

     jarves.asset_handler.css:
        class: "%jarves.asset_handler.css.class%"
        arguments: ["@jarves", "@jarves.filesystem.web", "@jarves.utils"]
        tags:
            - { name: jarves.asset_handler.loader, contentType: 'text/css', extension: css }

     jarves.dashboard.widget:
        class: Jarves\Controller\Admin\DashboardWidgets
        arguments: ['@jarves.cache.distributed']

     jarves.asset_handler.js:
        class: "%jarves.asset_handler.js.class%"
        arguments: ["@jarves", "@jarves.filesystem.web"]
        tags:
            - { name: jarves.asset_handler.loader, contentType: 'text/javascript', extension: js }


     jarves.cache.backend.files:
        class: Jarves\Cache\Backend\Files
        shared: false

     jarves.client.factory:
        class: Jarves\Client\ClientFactory
        arguments: ["@service_container", "@jarves.config"]

     jarves.client.abstract:
        class: Jarves\Client\ClientAbstract
        shared: false
        arguments: ["@jarves.config", "@jarves.page_stack"]

     jarves.client.jarves_users:
        class: Jarves\Client\JarvesUsers
        shared: false
        parent: jarves.client.abstract

     jarves.client.store.database:
        class: Jarves\Client\StoreDatabase
        shared: false

     jarves.markdowner:
        class: Jarves\ContentTypes\Markdowner
        arguments: ["@jarves.page_stack"]