parameters:
     jarves.plugin.userlogin.class: Jarves\Controller\Plugin\UserLogin

services:
  jarves.plugin.userlogin:
       class: "%jarves.plugin.userlogin.class%"
       arguments: ["@templating", "@jarves.page_stack", "@form.factory", "@jarves.user_operator"]