parameters:
     jarves.content.types.class: Jarves\ContentTypes\ContentTypes
     jarves.content.types.text.class: Jarves\ContentTypes\TypeText
     jarves.content.types.image.class: Jarves\ContentTypes\TypeImage
     jarves.content.types.plugin.class: Jarves\ContentTypes\TypePlugin
     jarves.content.types.markdown.class: Jarves\ContentTypes\TypeMarkdown
     jarves.content.types.tray.class: Jarves\ContentTypes\TypeTray
     jarves.content.types.html.class: Jarves\ContentTypes\TypeHtml

services:
     jarves.content.types.text:
         class: "%jarves.content.types.text.class%"

     jarves.content.types.image:
         class: "%jarves.content.types.image.class%"
         arguments: ["@jarves"]

     jarves.content.types.html:
         class: "%jarves.content.types.html.class%"

     jarves.content.types.plugin:
         class: "%jarves.content.types.plugin.class%"
         arguments: ["@jarves", "@jarves.page_stack", "@kernel", "@event_dispatcher", "@jarves.page_response.factory"]

     jarves.content.types.markdown:
         class: "%jarves.content.types.markdown.class%"
         arguments: ["@jarves.markdowner"]

     jarves.content.types.tray:
         class: "%jarves.content.types.tray.class%"
