parameters:
     jarves.field.types.class: Jarves\Admin\FieldTypes\FieldTypes
     jarves.field.types.text.class: Jarves\Admin\FieldTypes\TypeText
     jarves.field.types.theme.class: Jarves\Admin\FieldTypes\TypeTheme
     jarves.field.types.number.class: Jarves\Admin\FieldTypes\TypeNumber
     jarves.field.types.object.class: Jarves\Admin\FieldTypes\TypeObject
     jarves.field.types.datetime.class: Jarves\Admin\FieldTypes\TypeDatetime
     jarves.field.types.select.class: Jarves\Admin\FieldTypes\TypeSelect
     jarves.field.types.textboxList.class: Jarves\Admin\FieldTypes\TypeTextboxList
     jarves.field.types.checkbox.class: Jarves\Admin\FieldTypes\TypeCheckbox
     jarves.field.types.page.class: Jarves\Admin\FieldTypes\TypePage
     jarves.field.types.layout.class: Jarves\Admin\FieldTypes\TypeLayout
     jarves.field.types.lang.class: Jarves\Admin\FieldTypes\TypeLang
     jarves.field.types.textarea.class: Jarves\Admin\FieldTypes\TypeTextarea
     jarves.field.types.file.class: Jarves\Admin\FieldTypes\TypeFile
     jarves.field.types.image.class: Jarves\Admin\FieldTypes\TypeImage
     jarves.field.types.filelist.class: Jarves\Admin\FieldTypes\TypeFilelist
     jarves.field.types.layoutelement.class: Jarves\Admin\FieldTypes\TypeLayoutElement
     jarves.field.types.view.class: Jarves\Admin\FieldTypes\TypeView
     jarves.field.types.array.class: Jarves\Admin\FieldTypes\TypeArray
     jarves.field.types.pageContents.class: Jarves\Admin\FieldTypes\TypePageContents
     jarves.field.types.wysiwyg.class: Jarves\Admin\FieldTypes\TypeWysiwyg
     jarves.field.types.password.class: Jarves\Admin\FieldTypes\TypePassword
     jarves.field.types.userPassword.class: Jarves\Admin\FieldTypes\TypeUserPassword
     jarves.field.types.contentElements.class: Jarves\Admin\FieldTypes\TypeContentElements
     jarves.field.types.properties.class: Jarves\Admin\FieldTypes\TypeProperties

services:
     jarves.field.types:
         class: "%jarves.field.types.class%"
         arguments: ["@service_container"]

     jarves.field.types.text:
         class: "%jarves.field.types.text.class%"
         shared: false

     jarves.field.types.theme:
         class: "%jarves.field.types.theme.class%"
         shared: false

     jarves.field.types.number:
         class: "%jarves.field.types.number.class%"
         shared: false

     jarves.field.types.object:
         class: "%jarves.field.types.object.class%"
         arguments: ["@jarves.objects"]
         shared: false

     jarves.field.types.datetime:
         class: "%jarves.field.types.datetime.class%"
         shared: false

     jarves.field.types.select:
         class: "%jarves.field.types.select.class%"
         shared: false

     jarves.field.types.textboxList:
         class: "%jarves.field.types.textboxList.class%"
         shared: false

     jarves.field.types.checkbox:
         class: "%jarves.field.types.checkbox.class%"
         shared: false

     jarves.field.types.page:
         class: "%jarves.field.types.page.class%"
         shared: false

     jarves.field.types.layout:
         class: "%jarves.field.types.layout.class%"
         shared: false

     jarves.field.types.lang:
         class: "%jarves.field.types.lang.class%"
         shared: false

     jarves.field.types.textarea:
         class: "%jarves.field.types.textarea.class%"
         shared: false

     jarves.field.types.wysiwyg:
         class: "%jarves.field.types.wysiwyg.class%"
         shared: false

     jarves.field.types.file:
         class: "%jarves.field.types.file.class%"
         shared: false

     jarves.field.types.image:
         class: "%jarves.field.types.image.class%"
         shared: false

     jarves.field.types.filelist:
         class: "%jarves.field.types.filelist.class%"
         shared: false

     jarves.field.types.layoutelement:
         class: "%jarves.field.types.layoutelement.class%"
         shared: false

     jarves.field.types.view:
         class: "%jarves.field.types.view.class%"
         shared: false

     jarves.field.types.array:
         class: "%jarves.field.types.array.class%"
         shared: false

     jarves.field.types.pageContents:
         class: "%jarves.field.types.pageContents.class%"
         shared: false

     jarves.field.types.password:
         class: "%jarves.field.types.password.class%"
         shared: false

     jarves.field.types.userPassword:
         class: "%jarves.field.types.userPassword.class%"
         arguments: ["@jarves.config"]
         shared: false

     jarves.field.types.contentElements:
         class: "%jarves.field.types.contentElements.class%"
         shared: false

     jarves.field.types.properties:
         class: "%jarves.field.types.properties.class%"
         shared: false
